CREATE TABLE "Patota" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "User" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';
ALTER TABLE "User" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Player" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';

ALTER TABLE "Guest" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';

ALTER TABLE "Match" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';

ALTER TABLE "Transaction" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';

ALTER TABLE "WaitlistEntry" ADD COLUMN "patotaId" TEXT NOT NULL DEFAULT 'patota-becker-001';
